Repository Nixtla/mlforecast, pull requests merged in 2022-12, with the labels that each got.

#71 add MLForecast.from_cv
  mlforecast/_modidx.py
  mlforecast/core.py
  mlforecast/forecast.py
  mlforecast/lgb_cv.py
  nbs/core.ipynb
  nbs/docs/end_to_end_walkthrough.ipynb
  nbs/forecast.ipynb
  nbs/lgb_cv.ipynb
Labels: breaking

#72 allow models to be dict
  action_files/clean_nbs
  mlforecast/core.py
  mlforecast/distributed/core.py
  mlforecast/distributed/forecast.py
  mlforecast/forecast.py
  mlforecast/lgb_cv.py
  nbs/core.ipynb
  nbs/distributed.core.ipynb
  nbs/distributed.forecast.ipynb
  nbs/distributed.models.xgb.ipynb
  nbs/docs/end_to_end_walkthrough.ipynb
  nbs/forecast.ipynb
  nbs/lgb_cv.ipynb
Labels: feature

#73 replace predict_fn with callbacks
  .mypy.ini
  mlforecast/_modidx.py
  mlforecast/core.py
  mlforecast/distributed/core.py
  mlforecast/distributed/forecast.py
  mlforecast/forecast.py
  mlforecast/lgb_cv.py
  nbs/core.ipynb
  nbs/distributed.core.ipynb
  nbs/distributed.forecast.ipynb
  nbs/forecast.ipynb
  nbs/lgb_cv.ipynb
Labels: breaking

#76 [FEAT] Add cross-validation tutorial
  nbs/docs/cross_validation.ipynb
  nbs/sidebar.yml
Labels: documentation

#77 [FEAT] Add electricity peak forecasting tutorial
  nbs/docs/electricity_peak_forecasting.ipynb
  nbs/sidebar.yml
Labels: documentation

#78 [FIX] Improve description preprocessing ERCOT dataset
  nbs/docs/electricity_peak_forecasting.ipynb
Labels: documentation

#74 [FEAT] Add step size argument to cross validation method
  environment.yml
  mlforecast/_modidx.py
  mlforecast/distributed/forecast.py
  mlforecast/forecast.py
  mlforecast/lgb_cv.py
  mlforecast/utils.py
  nbs/distributed.forecast.ipynb
  nbs/forecast.ipynb
  nbs/lgb_cv.ipynb
  nbs/utils.ipynb
Labels: feature

#79 [FEAT] Add `new_data` argument to `predict` method (allow transferability)
  mlforecast/core.py
  mlforecast/distributed/forecast.py
  mlforecast/forecast.py
  nbs/core.ipynb
  nbs/distributed.forecast.ipynb
  nbs/forecast.ipynb
Labels: feature
