Repository Nixtla/mlforecast, pull requests merged in 2023-11, with the labels that each got.

#265 support lag transformations from coreforecast
  .github/workflows/ci.yaml
  environment.yml
  local_environment.yml
  mlforecast/_modidx.py
  mlforecast/compat.py
  mlforecast/core.py
  mlforecast/grouped_array.py
  mlforecast/lag_transforms.py
  nbs/compat.ipynb
  nbs/core.ipynb
  nbs/docs/how-to-guides/lag_transforms_guide.ipynb
  nbs/feature_engineering.ipynb
  nbs/grouped_array.ipynb
  nbs/lag_transforms.ipynb
  nbs/mint.json
  nbs/sidebar.yml
  pyproject.toml
  settings.ini
  setup.py
Labels: feature

#271 use backtest_splits from utilsforecast
  environment.yml
  local_environment.yml
  mlforecast/_modidx.py
  mlforecast/distributed/forecast.py
  mlforecast/forecast.py
  mlforecast/lgb_cv.py
  mlforecast/utils.py
  nbs/distributed.forecast.ipynb
  nbs/docs/getting-started/quick_start_distributed.ipynb
  nbs/forecast.ipynb
  nbs/lgb_cv.ipynb
  nbs/utils.ipynb
  settings.ini
Labels: enhancement

#273 Improve error message "Found missing inputs in X_df"
  mlforecast/core.py
  nbs/core.ipynb
Labels: enhancement

#276 fix RollingStd typo
  mlforecast/lag_transforms.py
  nbs/lag_transforms.ipynb
Labels: fix

#277 add sklearn pipelines guide
  nbs/docs/how-to-guides/sklearn_pipelines.ipynb
  nbs/mint.json
Labels: documentation
