Repository Nixtla/mlforecast, pull requests merged in 2023-01, with the labels that each got.

#81 [FEAT] Perform cross validation without refitting the models
  mlforecast/distributed/forecast.py
  mlforecast/forecast.py
  nbs/distributed.forecast.ipynb
  nbs/forecast.ipynb
Labels: enhancement, feature

#80 Support one model per horizon approach
  figs/index.png
  mlforecast/_modidx.py
  mlforecast/core.py
  mlforecast/distributed/forecast.py
  mlforecast/forecast.py
  nbs/core.ipynb
  nbs/distributed.forecast.ipynb
  nbs/docs/cross_validation.ipynb
  nbs/docs/electricity_peak_forecasting.ipynb
  nbs/figs/forecast__cross_validation.png
  nbs/figs/forecast__ercot.png
  nbs/figs/forecast__predict.png
  nbs/forecast.ipynb
Labels: feature

#82 [FIX] Remove `dynamic_dfs` argument from `cross_validation` method
  mlforecast/distributed/forecast.py
  mlforecast/forecast.py
  nbs/distributed.forecast.ipynb
  nbs/forecast.ipynb
Labels: fix

#85 [FEAT] Add nbdev merge to gitattributes
  .gitattributes
Labels: feature
