Repository Nixtla/mlforecast, pull requests merged in 2023-02, with the labels that each got.

#86 Add prediction (conformal) intervals
  mlforecast/_modidx.py
  mlforecast/forecast.py
  mlforecast/utils.py
  nbs/figs/forecast__cross_validation_intervals.png
  nbs/figs/forecast__predict_intervals.png
  nbs/figs/forecast__predict_intervals_window_size_1.png
  nbs/forecast.ipynb
  nbs/utils.ipynb
  settings.ini
Labels: feature

#89 automate release
  .github/release-drafter.yml
  .github/workflows/release.yml
Labels: maintenance

#87 Add prediction intervals tutorial
  nbs/docs/prediction_intervals.ipynb
  nbs/sidebar.yml
  settings.ini
Labels: documentation

#93 [DOCS] Add transfer learning tutorial
  nbs/docs/transfer_learning.ipynb
  nbs/sidebar.yml
Labels: documentation
