Repository Nixtla/mlforecast, pull requests merged in 2023-04, with the labels that each got.

#104 add ray integration
  environment.yml
  mlforecast/_modidx.py
  mlforecast/core.py
  mlforecast/distributed/forecast.py
  mlforecast/distributed/models/ray/__init__.py
  mlforecast/distributed/models/ray/lgb.py
  mlforecast/distributed/models/ray/xgb.py
  nbs/distributed.forecast.ipynb
  nbs/distributed.models.ray.lgb.ipynb
  nbs/distributed.models.ray.xgb.ipynb
  settings.ini
Labels: feature

#117 fix slack link in README
  README.md
  nbs/index.ipynb
Labels: documentation

#118 set lower bound on spark for tests
  environment.yml
Labels: maintenance

#119 Append new vals
  mlforecast/_modidx.py
  mlforecast/core.py
  mlforecast/grouped_array.py
  nbs/core.ipynb
  nbs/docs/end_to_end_walkthrough.ipynb
  nbs/grouped_array.ipynb
Labels: feature

#125 remove dynamic_dfs argument from LightGBMCV when it can be inferred
  environment.yml
  mlforecast/lgb_cv.py
  nbs/lgb_cv.ipynb
Labels: enhancement
