Repository Nixtla/mlforecast, pull requests merged in 2023-05, with the labels that each got.

#129 Allow intervals for horizon lower than window size
  mlforecast/forecast.py
  nbs/forecast.ipynb
Labels: enhancement

#134 use target_col in conformity scores
  mlforecast/forecast.py
  nbs/forecast.ipynb
Labels: fix

#137 extend custom metric signature in LightGBMCV and add example
  environment.yml
  mlforecast/lgb_cv.py
  nbs/lgb_cv.ipynb
Labels: enhancement

#140 use ruff for linting
  .github/workflows/lint.yaml
  .pylintrc
  action_files/lint
  environment.yml
  local_environment.yml
  pyproject.toml
  settings.ini
Labels: maintenance
