Repository Nixtla/mlforecast, pull requests merged in 2023-09, with the labels that each got.

#198 fix fitted_values methods
  mlforecast/_modidx.py
  mlforecast/core.py
  mlforecast/forecast.py
  mlforecast/grouped_array.py
  mlforecast/target_transforms.py
  mlforecast/utils.py
  nbs/core.ipynb
  nbs/forecast.ipynb
  nbs/grouped_array.ipynb
  nbs/target_transforms.ipynb
  nbs/utils.ipynb
Labels: fix

#204 raise error when max_horizon and models_ don't match
  mlforecast/forecast.py
  nbs/forecast.ipynb
Labels: enhancement

#206 support fitted inverse transform in LocalStandardScaler
  mlforecast/_modidx.py
  mlforecast/forecast.py
  mlforecast/target_transforms.py
  nbs/forecast.ipynb
  nbs/target_transforms.ipynb
Labels: fix

#196 Prediction intervals for machine learning models
  environment.yml
  local_environment.yml
  nbs/docs/prediction_intervals_in_forecasting_models.ipynb
  nbs/figs/prediction_intervals_in_forecasting_models__autocorrelation.png
  nbs/figs/prediction_intervals_in_forecasting_models__eda.png
  nbs/figs/prediction_intervals_in_forecasting_models__plot_forecasting_intervals.png
  nbs/figs/prediction_intervals_in_forecasting_models__plot_residual_model.png
  nbs/figs/prediction_intervals_in_forecasting_models__plot_values.png
  nbs/figs/prediction_intervals_in_forecasting_models__seasonal_decompose_aditive.png
  nbs/figs/prediction_intervals_in_forecasting_models__seasonal_decompose_multiplicative.png
  nbs/figs/prediction_intervals_in_forecasting_models__train_test.png
  nbs/sidebar.yml
  nbs/utils.ipynb
Labels: documentation

#215 remove differences argument
  mlforecast/core.py
  mlforecast/distributed/forecast.py
  mlforecast/forecast.py
  mlforecast/lgb_cv.py
  nbs/core.ipynb
  nbs/distributed.forecast.ipynb
  nbs/forecast.ipynb
  nbs/lgb_cv.ipynb
Labels: breaking change
