Repository Nixtla/mlforecast, pull requests merged in 2024-08, with the labels that each got.

#399 make season_length optional in AutoMLForecast
  mlforecast/auto.py
  nbs/auto.ipynb
  settings.ini
Labels: enhancement

#397 Clear up the README for the new user
  README.md
  nbs/index.ipynb
Labels: documentation

#406 feat: mlflow flavor
  .gitignore
  .pre-commit-config.yaml
  mlforecast/_modidx.py
  mlforecast/flavor.py
  nbs/docs/how-to-guides/mlflow.ipynb
  nbs/mint.json
  settings.ini
Labels: feature

#408 use TypeVar for dataframes and distribute py.typed file
  mlforecast/core.py
  mlforecast/forecast.py
  mlforecast/py.typed
  nbs/core.ipynb
  nbs/forecast.ipynb
  settings.ini
Labels: enhancement
